default_install_hook_types:
  - pre-commit
  - commit-msg
  - pre-push
default_stages:
  - pre-commit
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.4.0'
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: '0.23.0'
    hooks:
      - id: check-github-workflows
        files: ^(\.github/|)workflows/[^/]+$

  - repo: https://github.com/commitizen-tools/commitizen
    rev: 'v3.13.0'
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages: [pre-push]
