name: Linters

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  pre-commit:
    uses: ./.github/workflows/pre-commit.yaml

  gitlint:
    uses: ./.github/workflows/gitlint.yaml
    with:
      first-commit: 13ae0fa
