name: Commitizen

on:
  workflow_call:

jobs:
  commitizen:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # Check out any possible commitizen config file.
          # Nonexistent files will be ignored.
          sparse-checkout: |
            .cz.toml
            .cz.json
            .cz.yaml
            cz.json
            cz.yaml
            pyproject.toml
            README.md
          sparse-checkout-cone-mode: false

      - name: Install commitizen
        run: pipx install commitizen

      - name: Check commit message format
        shell: bash
        run: cz check --rev-range origin/${{ github.event.repository.default_branch }}..HEAD
