name: Docker

on:
  workflow_call:
    inputs:
      build-platforms:
        required: false
        type: string
        default: linux/amd64,linux/arm64/v8,linux/arm/v7
      tag-latest:
        required: false
        type: boolean
        default: false

jobs:
  lint:
    runs-on: ubuntu-latest
    outputs:
      results: ${{ steps.hadolint.outputs.results }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run hadolint
        id: hadolint
        uses: hadolint/hadolint-action@v3.1.0

  comment-lint-results:
    runs-on: ubuntu-latest
    needs: [lint]
    if: always()
    steps:
      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: find-comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: '### Hadolint results'

      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ### Hadolint results

            ```
            ${{ needs.lint.outputs.results }}
            ```

          edit-mode: replace

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: "ghcr.io/${{ github.repository }}"
          tags: |
            type=ref,event=pr
            type=semver,pattern=v{{major}}
            type=semver,pattern=v{{version}}
            type=raw,value=edge,enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) && inputs.tag-latest }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: ${{ inputs.build-platforms }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
