name: Tests

on:
  workflow_call:
    inputs:
      python-version:
        type: string
        required: true

jobs:
  pytest:
    runs-on: ubuntu-latest
    name: pytest-${{ inputs.python-version }}
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - name: Set up python environment
        uses: actions/setup-python@v4
        with:
          cache: 'poetry'
          python-version: ${{ inputs.python-version }}

      - run: poetry install --no-root --with=tests --sync

      - run: poetry run pytest --cov-report=xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          name: coverage-${{ inputs.python-version }}
